### ISSUE TITLE
Collapse Output Data

### ISSUE THREAD

**Issue by NightKhaos** [awslabs/cloudformation-accustom#4]
When trying to access nested variables inside the output dictionary CloudFormation cannot directly access nested variables, i.e. trying to access the `!GetAtt Resource.Address.Street` with the following will fail.

    {
       "Address" {
            "Street" : "Apple Street"
      }
    }

So, we need to parse the response, and replace children with . notation, e.g.:

    {
       "Address.Street" : "Apple Street"
    }

**Comment by taylorb-syd** [comment]
Introduced this functionality into `issue-4` branch, which has been merged into `main`. Unit testing works, but still requires functional testing.
