### ISSUE TITLE
Use `wrapt` for implementing decorators

### ISSUE THREAD

**Issue by garyd203** [awslabs/cloudformation-accustom#8]
The [wrapt](https://pypi.org/project/wrapt/) library provides out-of-the-box handling for implementing decorators correctly, including all the weird corner cases that mere mortals like us don't even know exist. You might find that it makes your decorators easier to implement and/or reason about.

Thanks for the chat this evening. Feel free to close this issue if you don't think it's relevant :-)

**Comment by NightKhaos** [comment]
One of the my design goals of the library is that it should have no external dependancies, apart from itself, to run in Lambda. I will need to look into this library a bit and see if it worth it, because it will need to be included in the library as a "vendored" copy if I decide to use it.

**Comment by garyd203** [comment]
Yeah, fair enough, packaging dependencies for Lambda can be tricky and off-putting, so I understand your design goal. Cheers!

**Comment by taylorb-syd** [comment]
Since I now have other dependencies that need to be installed for this library I will be implementing this as part of the 2.0 release as, unlike `requests`, we do not have a fallback library with people using older versions of `botocore`.

**Comment by taylorb-syd** [comment]
Closing as the design model has changed considerably since this request was made. I will be evaluating libraries like these to see if they help make the code cleaner and easier to follow. See #26 for more details.
